### ISSUE TITLE
GenomicDistributions not compatible with R >=4.0?

### ISSUE THREAD

**Issue by steph-e** [databio/GenomicDistributions#145]
What version of R does Genomic distributions package require? In the description it states R >=4.0 however I am using R 4.0.3 and getting this error

```
> BiocManager::install("GenomicDistributions",lib='/home/rstudio/rstudio-user-libs')
'getOption("repos") replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org/

Bioconductor version 3.12 (BiocManager 1.30.12), R 4.0.3 (2020-10-10)
Installing package(s) 'GenomicDistributions'
Warning message:
package ‘GenomicDistributions’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

**Comment by kkupkova** [comment]
Hi, this might have to do something with the package being part of the development version of Bioconductor. You can try installing the package from GitHub, which should solve your issues:
`devtools::install_github("databio/GenomicDistributions")`

And if you have problem installing GenomicDistributionsData too, you can install it in following way: 
`install.packages("http://big.databio.org/GenomicDistributionsData/GenomicDistributionsData_0.0.2.tar.gz", repos=NULL)`

I hope this helps!

**Comment by nsheff** [comment]
Yes, GenomicDistributions is still only in the devel version of bioconductor. It will be included with the next release.

So if you want to use devel packages from bioconductor, you can also try this from the [bioconductor page](https://bioconductor.org/packages/devel/bioc/html/GenomicDistributions.html):

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("GenomicDistributions")
```

but I think Bioc devel will require R version 4.1 at the moment.

In the meantime, you can also just install direclty from github instead of going through bioconductor, as @kkupkova mentioned.
