### ISSUE TITLE
Genomic partitions plot frequencies not per set

### ISSUE THREAD

**Issue by ChristelKrueger** [databio/GenomicDistributions#189]
Thanks for this handy package!

When I plot the distribution across genomic partitions for more than one region set, the frequencies seem to be calculated across all sets rather than per set. This doesn't seem to be the case in the worked example (http://code.databio.org/GenomicDistributions/articles/intro.html)
Is this a bug or am I doing something wrong?

[frequency_distribution_test_220131.pdf](https://github.com/databio/GenomicDistributions/files/7969836/frequency_distribution_test_220131.pdf)

**Comment by kkupkova** [comment]
Hi Christel, 

this issue has been fixed in the new version of GenomicDistributions. Please try to install the latest version of GenomicDistributions. The easiest way would probably be ti install it with devtools with following command: 

`devtools::install_github("databio/GenomicDistributions")`

Alternatively you can install it also from a development version from Bioconductor:

https://www.bioconductor.org/packages/devel/bioc/html/GenomicDistributions.html

**Comment by ChristelKrueger** [comment]
Got it now - thank you!
