### ISSUE TITLE
Add example graphs to documentation?

### ISSUE THREAD

**Issue by endrebak** [databio/GenomicDistributions#64]
Thanks for the interesting package. Graphs in the docs would be nice, so I do not have to install and play around with it to understand the graphs it can produce.

**Comment by nsheff** [comment]
Is this what you're looking for?

http://code.databio.org/GenomicDistributions/articles/intro.html

We need to update these docs with the recent changes, though. It shows the release version, not dev.

**Comment by endrebak** [comment]
How embarrassing, yes! I was looking here at the individual functions: http://code.databio.org/GenomicDistributions/reference/index.html

Thanks for the great package.

**Comment by nsheff** [comment]
glad that helped. by the way, we have a lot of updates hanging out on the dev branch, including several new plot types and some very important updates to those existing ones... so might want to take a look there (but you'd have to build the vignette yourself). it might not quite be functional though since it's dev. I'll try to get a chance to make an interim release soon if it would help.

**Comment by endrebak** [comment]
Do not rush it for my sake, but thanks for offering 👍🏻

**Comment by nsheff** [comment]
well, I've just polished up the dev branch dramatically. it works well now. Take look at it if you're interested, there's lots of new stuff to play around with.

will have a new release shortly.
