### ISSUE TITLE
percentage partition plots questions

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#90]
The current vignette shows a corrected partition plot that uses 'backgroundGR'. We need to figure out exactly how this differs from the expected partition distribution plots; are these different concepts worthy of different plots? should they be merged? 

Should the expected partition plot be made flexible enough to accept a background argument, which defaults to 'the whole genome' if none is provided ?

Side note: the percentage plots also shift the order of the inputs, which seems strange.

**Comment by joseverdezoto** [comment]
@nsheff  the incomplete version of the percentage function had a `backgroundGR` argument
https://github.com/databio/GenomicDistributions/blob/fab3065ea074cb20aa17bf79fe11065909d7a124/R/partition-plots.R#L596

I assumed that object  was provided as a way to normalize the overlaps calculated for different regionsets. But even if that was the original intention, I'm not sure if it makes sense to normalize percentages instead of raw overlaps 
https://github.com/databio/GenomicDistributions/blob/fab3065ea074cb20aa17bf79fe11065909d7a124/R/partition-plots.R#L605-L614
